<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.6</version>
    </parent>

    <groupId>eu.xfsc.tsa.sign</groupId>
    <artifactId>sign-service</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>sign-service</name>
    <description>Eclipse XFSC TSA Signer service</description>
    <inceptionYear>2024</inceptionYear>
    <organization>
        <name>T-Systems International</name>
    </organization>
    <url>${repository.url}/${repository.path}</url>

    <scm>
        <connection>scm:git:git://gitlab.eclipse.org/${repository.path}.git</connection>
        <url>${repository.url}/${repository.path}</url>
        <tag>HEAD</tag>
    </scm>
    <issueManagement>
        <system>GitLab</system>
        <url>${repository.url}/${repository.path}/-/issues</url>
    </issueManagement>
    <ciManagement>
        <url>${repository.url}/${repository.path}/-/pipelines</url>
    </ciManagement>

    <developers>
        <developer>
            <name>Denis Sukhoroslov</name>
            <email>denis.sukhoroslov@telekom.com</email>
        </developer>
    </developers>

    <repositories>
        <repository>
            <id>danubetech-maven-public</id>
            <url>https://repo.danubetech.com/repository/maven-public/</url>
        </repository>
    </repositories>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!-- -->
        <repository.url>https://gitlab.eclipse.org</repository.url>
        <repository.path>eclipse/xfsc/tsa/signer-j</repository.path>
        <!-- dependencies -->
        <spring-security.version>6.3.1</spring-security.version>
        <springdoc.version>2.2.0</springdoc.version>
        <jakarta.apis.version>3.1.0</jakarta.apis.version>
        <liquibase.version>4.27.0</liquibase.version>
        <lombok.version>1.18.32</lombok.version>
        <spring-vault.version>3.1.1</spring-vault.version>
        <micrometer.version>1.11.3</micrometer.version>
        <topbraid.version>1.4.2</topbraid.version>
        <vc.version>1.2.0</vc.version>
        <key-format.version>1.8.0</key-format.version>
        <did.version>1.4.0</did.version>
        <titanium.version>1.3.2</titanium.version>
        <jose4j.version>0.9.3</jose4j.version>
        <uni-resolver.version>0.17.0</uni-resolver.version>
        <ld-signatures.version>1.9.0</ld-signatures.version>
        <!-- test libs -->
        <embedded.postgres.version>2.0.6</embedded.postgres.version>
        <embedded.postgres.test.version>2.4.0</embedded.postgres.test.version>
        <skyscreamer.jsonassert.version>1.5.0</skyscreamer.jsonassert.version>
        <mockwebserver.version>4.11.0</mockwebserver.version>
        <!-- plugins -->
        <plugin.jacoco.version>0.8.11</plugin.jacoco.version>
        <plugin.openapi-generator.version>7.7.0</plugin.openapi-generator.version>
        <!--jib-->
        <ci-registry>${env.HARBOR_HOST}/${env.HARBOR_PROJECT}</ci-registry>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <!--dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency-->
        <!--dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
            <version>${spring-security.version}</version>
        </dependency-->
        <!--dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
            <version>${spring-security.version}</version>
        </dependency-->

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc.version}</version>
        </dependency>
        <!--dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>${jakarta.apis.version}</version>
        </dependency-->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>${jakarta.apis.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>8.0.1.Final</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.vault</groupId>
            <artifactId>spring-vault-core</artifactId>
            <version>${spring-vault.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>1.78.1</version>
        </dependency>
        <!-- DB -->
        <!--dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>${liquibase.version}</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.zonky.test</groupId>
            <artifactId>embedded-postgres</artifactId>
            <version>${embedded.postgres.version}</version>
        </dependency-->
        <!-- DID, VC, etc -->
        <dependency>
            <groupId>com.apicatalog</groupId>
            <artifactId>titanium-json-ld</artifactId>
            <version>${titanium.version}</version>
        </dependency>
        <dependency>
            <groupId>com.danubetech</groupId>
            <artifactId>verifiable-credentials-java</artifactId>
            <version>${vc.version}</version>
        </dependency>
        <dependency>
            <groupId>com.danubetech</groupId>
            <artifactId>key-formats-java</artifactId>
            <version>${key-format.version}</version>
        </dependency>
        <dependency>
            <groupId>decentralized-identity</groupId>
            <artifactId>did-common-java</artifactId>
            <version>${did.version}</version>
        </dependency>
        <dependency>
            <groupId>decentralized-identity</groupId>
            <artifactId>uni-resolver-client</artifactId>
            <version>${uni-resolver.version}</version>
        </dependency>
        <dependency>
            <groupId>decentralized-identity</groupId>
            <artifactId>uni-resolver-local</artifactId>
            <version>${uni-resolver.version}</version>
        </dependency>
        <dependency>
            <groupId>info.weboftrust</groupId>
            <artifactId>ld-signatures-java</artifactId>
            <version>${ld-signatures.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <!-- Test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!--dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency-->
        <!--dependency>
            <groupId>io.zonky.test</groupId>
            <artifactId>embedded-database-spring-test</artifactId>
            <version>${embedded.postgres.test.version}</version>
            <scope>test</scope>
        </dependency-->
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <version>${skyscreamer.jsonassert.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <!--version>3.2.6</version-->
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${plugin.openapi-generator.version}</version>
                <configuration>
                    <generateApiTests>false</generateApiTests>
                    <generateModelTests>false</generateModelTests>
                    <generateApiDocumentation>true</generateApiDocumentation>
                    <generateModelDocumentation>true</generateModelDocumentation>
                    <generateSupportingFiles>true</generateSupportingFiles>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-signer-server</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi/signer_openapi.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <packageName>eu.xfsc.tsa.sign.generated</packageName>
                            <skipValidateSpec>false</skipValidateSpec>
                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <configOptions>
                                <booleanGetterPrefix>is</booleanGetterPrefix>
                                <disallowAdditionalPropertiesIfNotPresent>false</disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>springdoc</documentationProvider>
                                <performBeanValidation>true</performBeanValidation>
                                <useBeanValidation>true</useBeanValidation>
                                <useTags>true</useTags>
                                <library>spring-boot</library>
                                <delegatePattern>true</delegatePattern>
                                <openApiNullable>false</openApiNullable>
                                <useJakartaEe>true</useJakartaEe>
                                <useSwaggerUI>true</useSwaggerUI>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSpringController>true</useSpringController>
                                <useOneOfInterfaces>false</useOneOfInterfaces>
                                <!--additionalModelTypeAnnotations>@lombok.NoArgsConstructor @lombok.AllArgsConstructor</additionalModelTypeAnnotations-->
                                <generateBuilders>true</generateBuilders>
                                <generatedConstructorWithRequiredArgs>true</generatedConstructorWithRequiredArgs>
                                <basePackage>eu.xfsc.tsa.sign.generated</basePackage>
                                <apiPackage>eu.xfsc.tsa.sign.generated.controller</apiPackage>
                                <modelPackage>eu.xfsc.tsa.sign.generated.model</modelPackage>
                                <configPackage>eu.xfsc.tsa.sign.generated.config</configPackage>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <skipDefaultInterface>false</skipDefaultInterface>
                                <dateLibrary>java8</dateLibrary>
                                <sourceFolder>/</sourceFolder>
                                <resourceFolder>/</resourceFolder>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${plugin.jacoco.version}</version>                
                <configuration>
                    <excludes>
                        <exclude>**/generated/interfaces/**</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>nimbus-jose-jwt</artifactId>
                <version>9.37.3</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
